### PR TITLE
Create pt_BR.txt

### PR DESCRIPTION
**Pull request by carmo-evan**

### CODE REVIEW

**Comment by dohliam** [comment]
@carmo-evan Wow, this is fantastic -- thanks so much! :tada: 

Would it be possible to convert the entry headwords to regular/lower case rather than uppercase? In other words, they should all be lowercase other than proper nouns and other words that would normally be capitalized. One way to do this could be to compare the list of headwords with an existing dictionary file -- the [Aspell dictionary for Brazilian Portuguese](https://ftp.gnu.org/gnu/aspell/dict/pt_BR/) for example has about 310K entries so it might be sufficient for this purpose, but maybe there is an easier/more accurate way to do this on your end?

**Comment by carmo-evan** [comment]
Hi @dohliam !

Let me try to come up with a script and I'll let you know.

Thank you,

Evan

**Comment by dohliam** [comment]
@carmo-evan Awesome! Thanks again. Let me know if there's anything I can help with :smile:

**Comment by dohliam** [comment]
@carmo-evan I'm going to merge this for now as others may be interested in using this data in the meantime. If you (or anyone else) is able to figure out a script to correct the capitalization of proper nouns please feel free to open a separate PR.

Thanks again for providing this! :+1:

**Pull request merged**
